### ISSUE TITLE
Enhance the UI design 

### ISSUE THREAD

**Issue by psy-pri** [psy-pri/twitter-analyser#4]

**Comment by PranavTrip** [comment]
Hey ! Kindly provide the issue description. I would like to contribute.

**Comment by psy-pri** [comment]
@PranavTrip Hey, you can try making the UI more attractive by changing the CSS (changing font, color scheme, etc.) primarily for ``search.html`` file though you can do it for the other html files too.

**Comment by PranavTrip** [comment]
@psy-pri sure I will work on UI and make it look better. Please assign this to me.

**Comment by psy-pri** [comment]
@PranavTrip assigned, keep me posted :)
